// nm_files.js — the demo project's files + a small vs-dark syntax highlighter.
//
// PROVENANCE (be precise about what is real here):
//  • config.yaml         — VERBATIM from the product's DEMO_CONFIG_YAML fixture.
//  • common/*.py         — the function bodies are VERBATIM from the product's
//                          DEMO_INDICATORS_PY / DEMO_SIGNALS_PY / DEMO_UTILS_PY
//                          fixtures. Only the header comments were translated to
//                          English and the mock-layer "(mock)" marker dropped —
//                          these files stand in for a user's project, not for the
//                          mock layer itself.
//  • strategy.py         — COMPOSED, not copied. The product's own strategy.py
//                          fixture is a mock-mode stub. This one is assembled from
//                          things that ARE authoritative: the documented contract
//                          (strategy_authoring.md) and the exact helper defs, signal
//                          line and sizing line that the real Strategy Builder emits
//                          (verified char-for-char against strategy_codegen.py).
//                          It is what a real user's file looks like — it is not a
//                          file that exists in the repo.
//
// File naming note: the mock layer stores this project's config as
// "demo_strategy_config.yaml", but REQUIRED_FILES, the allowed-paths hint
// ("top-level *.py / config.yaml / common/*.py") and the Builder's "Merge into
// strategy.config in config.yaml" all agree on config.yaml. The mock's
// "{stem}_config.yaml" is the snapshot download name. config.yaml is used here.

const NM_FILES = (function () {
  'use strict';

  const files = {
    'strategy.py': `# demo_strategy — spot, equal-weight when the signal fires.
#
# Contract (strategy_authoring.md): return {symbol: {'weight': float}}.
# You do NOT put any credentials in here — your userkey is injected
# automatically when you publish.
import numpy as np
import pandas as pd


# --- generated by the Builder: RSI — Relative Strength Index ---
# close/high/low/volume are per-symbol Series (e.g. ohlcv['close'].unstack(level=0)[sym])
def _rsi(s, period=14):
    delta = s.diff()
    gain = delta.clip(lower=0)
    loss = (-delta).clip(lower=0)
    avg_gain = gain.ewm(alpha=1.0/period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1.0/period, min_periods=period, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    return 100.0 - (100.0 / (1.0 + rs))


# --- generated by the Builder: MACD — Moving Average Convergence Divergence ---
def _ema(s, period=20):
    return s.ewm(span=period, adjust=False).mean()


def _macd(s, fast=12, slow=26, signal=9):
    ema_f = _ema(s, fast)
    ema_s = _ema(s, slow)
    macd_line = ema_f - ema_s
    signal_line = _ema(macd_line, signal)
    hist = macd_line - signal_line
    return macd_line, signal_line, hist


def strategy(data, config_dict=None):
    ohlcv = data['ohlcv']
    assets = config_dict.get('assets', ['BTCUSDT', 'ETHUSDT']) if config_dict else ['BTCUSDT', 'ETHUSDT']
    close_all = ohlcv['close'].unstack(level=0)

    weights = {}
    for asset in assets:
        close = close_all[asset]

        rsi = _rsi(close, period=14)
        macd_line, macd_signal, macd_hist = _macd(close, fast=12, slow=26, signal=9)

        # signal condition — assign weight to the asset when True (adapt to your logic)
        signal = (rsi.iloc[-1] < 30) and (macd_line.iloc[-1] > 0)

        # position sizing — equal weight (insert inside the asset loop, after signal)
        weights[asset] = {'weight': round(1.0 / max(len(assets), 1), 4) if signal else 0.0}

    return weights
`,

    'config.yaml': `version: "2.0"
system:
  trade_type: spot
  trade_env: demo
  rebalancing_interval_hours: 8
strategy:
  name: demo_strategy
  assets: [BTCUSDT, ETHUSDT]
  frequency: "1m"
  data:
    ohlcv: 240
live:
  end_date: "2026-12-31 00:00"
  spot:
    quote_coin: usdt
    total_allocation: 0.8
`,

    'common/__init__.py': `# common package
`,

    'common/indicators.py': `# common/indicators.py — your own indicator module
import pandas as pd
import numpy as np

def sma(series: pd.Series, period: int = 20) -> pd.Series:
    return series.rolling(period).mean()

def ema(series: pd.Series, period: int = 20) -> pd.Series:
    return series.ewm(span=period, adjust=False).mean()

def rsi(series: pd.Series, period: int = 14) -> pd.Series:
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def bollinger_bands(series: pd.Series, period: int = 20, std_dev: float = 2.0):
    mid = sma(series, period)
    std = series.rolling(period).std()
    return {'upper': mid + std_dev * std, 'mid': mid, 'lower': mid - std_dev * std}
`,

    'common/signals.py': `# common/signals.py — signal helpers

def cross_above(fast, slow):
    """fast crosses above slow"""
    return (fast > slow) & (fast.shift(1) <= slow.shift(1))

def cross_below(fast, slow):
    """fast crosses below slow"""
    return (fast < slow) & (fast.shift(1) >= slow.shift(1))

def threshold_filter(series, upper=70, lower=30):
    """upper/lower bound filter, e.g. for RSI"""
    return {'overbought': series > upper, 'oversold': series < lower}
`,

    'common/utils.py': `# common/utils.py — shared utilities
import datetime

def nowtime():
    return datetime.datetime.utcnow()

def safe_divide(a, b, default=0.0):
    return a / b if b != 0 else default
`,
  };

  // ── highlighter ──────────────────────────────────────────────────────────
  // A <pre> on #1e1e1e with these colors IS vs-dark — Monaco's own background is
  // #1e1e1e, so this matches the real editor closely without shipping Monaco.
  //
  // Single-pass, character-by-character tokenizer (no regex placeholder tricks —
  // those are what let a NUL sentinel slip into an earlier version of this file).
  // Emits already-escaped HTML, so it never double-escapes span markup.
  const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const KW = new Set('def return import from for in if else elif and or not None True False class try except with as lambda while break continue pass raise yield global is del assert'.split(' '));

  function pyLine(line) {
    let out = '', i = 0;
    const n = line.length;
    while (i < n) {
      const c = line[i];
      // comment to end of line
      if (c === '#') { out += '<span class="cm">' + esc(line.slice(i)) + '</span>'; break; }
      // string literal (single/double, with backslash escapes)
      if (c === '"' || c === "'") {
        let j = i + 1;
        while (j < n && !(line[j] === c && line[j - 1] !== '\\')) j++;
        out += '<span class="st">' + esc(line.slice(i, Math.min(j + 1, n))) + '</span>';
        i = j + 1; continue;
      }
      // identifier / keyword / function-call
      if (/[A-Za-z_]/.test(c)) {
        let j = i + 1;
        while (j < n && /[A-Za-z0-9_]/.test(line[j])) j++;
        const word = line.slice(i, j);
        if (KW.has(word)) out += '<span class="kw">' + word + '</span>';
        else if (line[j] === '(') out += '<span class="fn">' + esc(word) + '</span>';
        else out += esc(word);
        i = j; continue;
      }
      // number
      if (/[0-9]/.test(c)) {
        let j = i + 1;
        while (j < n && /[0-9.]/.test(line[j])) j++;
        out += '<span class="nu">' + line.slice(i, j) + '</span>';
        i = j; continue;
      }
      out += esc(c); i++;
    }
    return out;
  }

  function ymlLine(line) {
    let code = line, tail = '', hash = -1, q = null;
    for (let i = 0; i < line.length; i++) {
      const c = line[i];
      if (q) { if (c === q) q = null; }
      else if (c === '"' || c === "'") q = c;
      else if (c === '#') { hash = i; break; }
    }
    if (hash >= 0) { code = line.slice(0, hash); tail = '<span class="cm">' + esc(line.slice(hash)) + '</span>'; }
    const m = code.match(/^(\s*)([\w.-]+)(:)(.*)$/);
    if (!m) return esc(code) + tail;
    const val = esc(m[4])
      .replace(/"[^"]*"|'[^']*'/g, s => '<span class="st">' + s + '</span>')
      .replace(/(\s)(\d+\.?\d*)(\s|$)/g, '$1<span class="nu">$2</span>$3');
    return m[1] + '<span class="yk">' + m[2] + '</span>:' + val + tail;
  }

  function highlight(src, lang) {
    const f = lang === 'yaml' ? ymlLine : pyLine;
    return src.replace(/\n$/, '').split('\n').map(f).join('\n');
  }

  return Object.assign(files, { highlight });
})();
